### ISSUE TITLE
Router probably should not import component modules

### ISSUE THREAD

**Issue by Phantom-Shen** [David3567/FRE-Training-Summer-01#52]
https://github.com/David3567/FRE-Training-Summer-01/blob/dbc35bf9e50940fbccea4c888d953421f19bab2e/ThunderStrikes/src/app/modules/app-routing/app-routing.module.ts#L26-L27

When I try to import the router in a core component, like "movie-dashborad.component", this will cause an infinite stack call. After, moving imported "movie-dashboad.module" from "app-routing.module" to "app.module", I can use the "[routerLink]" in "movie-dashboad.component.html" again. So, I think router should only be responsible for routing. We can import component modules in "app.module", or create another layer of module to control all the components module, so we can leave "app.module" unchanged and never touch it again.

**Comment by victorincode** [comment]
https://github.com/David3567/FRE-Training-Summer-01/pull/54

**Comment by victorincode** [comment]
Bug was fixed in #69.
